- hosts: localhost
  become: true
  tasks:
    - ansible.builtin.import_tasks: tasks/pacman_packages.yaml
      become: yes
      become_user: root

    - ansible.builtin.import_tasks: tasks/add_defkit.yaml
      become: yes
      become_user: root

    - ansible.builtin.import_tasks: tasks/configs.yaml
      become: yes
      become_user: defkit
